<?php

module_load_include('inc', 'setlist', 'setlist.entities');

/**
* Implementation of hook_menu().
*/
function setlist_menu() {
  $items['musicians'] = array(
  'title' => 'Musicians',
  'page callback' => 'setlist_musicians',
  'access callback' => TRUE,
  'type' => MENU_NORMAL_ITEM,
  );

  $items['musician/%'] = array(
    'title' => 'Musician',
    'page callback' => 'setlist_view_musician',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
  );

  $items['instruments'] = array(
  'title' => 'Instruments',
  'page callback' => 'setlist_instruments',
  'access callback' => TRUE,
  'type' => MENU_NORMAL_ITEM,
  );

  $items['instruments/%'] = array(
    'title' => 'Instruments',
    'page callback' => 'setlist_view_instrument',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
  );
      
  $items['songs'] = array(
  'title' => 'Songs',
  'page callback' => 'setlist_songs',
  'access callback' => TRUE,
  'type' => MENU_NORMAL_ITEM,
  );

  $items['song/%'] = array(
    'title' => 'Song',
    'page callback' => 'setlist_view_song',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
  );

  return $items;
}

/**
* Musicians callback.
*/
function setlist_musicians() {
  $musicians = entity_load('musician', array(1));

  $list = entity_view('musician', $musicians);

  $output = array();

  foreach ($list['musician'] as $musician) {
    $output[] = drupal_render($musician);
  }

  return implode($output);
}

/**
* Instruments callback.
*/
function setlist_instruments() {
  $instruments = entity_load('instrument', array(1));

  $list = entity_view('instrument', $instruments);

  $output = array();

  foreach ($list['instrument'] as $instrument) {
    $output[] = drupal_render($instrument);
  }

  dpm($output);

  return implode($output);
}

/**
* Songs callback.
*/
function setlist_songs() {
  $songs = entity_load('song', array(1));

  $list = entity_view('song', $songs);

  $output = array();

  foreach ($list['song'] as $song) {
    $output[] = drupal_render($song);
  }

  return implode($output);
}

/**
 * Callback function for displaying the individual song page
 */
function setlist_view_song($id) {

  $songs = entity_load('song', array($id));
  $song = $songs[$id];

  drupal_set_title($song->name);
  $output = entity_view('song', array($song));
  
  return $output;
}

/**
 * Callback function for displaying the individual musician page
 */
function setlist_view_musician($id) {

  $musicians = entity_load('musician', array($id));
  $musician = $musicians[$id];

  drupal_set_title($musician->name);
  $output = entity_view('musician', array($musician));
  
  return $output;

}

/**
 * Callback function for displaying the individual instrument page
 */
function setlist_view_instrument($id) {

  $instruments = entity_load('instrument', array($id));
  $instrument = $instruments[$id];

  drupal_set_title($instrument->name);
  $output = entity_view('instrument', array($instrument));
  
  return $output;

}

/**
 * Form definition for adding / editing a song.
 */
function song_form($form, &$form_state, $song = NULL) {

  $form['name'] = array(
    '#title' => t('Song name'),
    '#type' => 'textfield',
    '#default_value' => isset($song->name) ? $song->name : '',
    '#required' => TRUE,
  );

  $form['genre'] = array(
    '#title' => t('Song genre'),
    '#type' => 'textfield',
    '#default_value' => isset($song->genre) ? $song->genre : '',
    '#required' => TRUE,
  );

  $form['year'] = array(
    '#title' => t('Song year'),
    '#type' => 'textfield',
    '#default_value' => isset($song->year) ? $song->year : '',
    '#required' => TRUE,
  );  
  
  $form['submit'] = array(
    '#type' => 'submit', 
    '#value' => isset($song->id) ? t('Update song') : t('Save song'),
    '#weight' => 50,
  );

  field_attach_form('song', $song, $form, $form_state);

  return $form;
}

function _song_form_validate(&$form, &$form_state) {
  //drupal_set_message('hi from validation');
}

/**
 * Submit handler for the song add/edit form.
 */
function song_form_submit($form, &$form_state) {
  $song = entity_ui_form_submit_build_entity($form, $form_state);
  $song->save();
  drupal_set_message(t('The song: @name has been saved.', array('@name' => $song->name)));
  $form_state['redirect'] = 'admin/songs';
}

/**
 * Form definition for adding / editing a musician.
 */
function musician_form($form, &$form_state, $musician = NULL) {

  $form['name'] = array(
    '#title' => t('Musician name'),
    '#type' => 'textfield',
    '#default_value' => isset($musician->name) ? $musician->name : '',
    '#required' => TRUE,
  );

  $form['submit'] = array(
    '#type' => 'submit', 
    '#value' => isset($musician->id) ? t('Update musician') : t('Save musician'),
    '#weight' => 50,
  );

  field_attach_form('musician', $musician, $form, $form_state);

  return $form;
}

/**
 * Submit handler for the musician add/edit form.
 */
function musician_form_submit($form, &$form_state) {
  $musician = entity_ui_form_submit_build_entity($form, $form_state);
  $musician->save();
  drupal_set_message(t('The musician: @name has been saved.', array('@name' => $musician->name)));
  $form_state['redirect'] = 'admin/musicians';
}

/**
 * Form definition for adding / editing a instrument.
 */
function instrument_form($form, &$form_state, $instrument = NULL) {

  $form['name'] = array(
    '#title' => t('Instrument name'),
    '#type' => 'textfield',
    '#default_value' => isset($instrument->name) ? $instrument->name : '',
    '#required' => TRUE,
  );

  $form['submit'] = array(
    '#type' => 'submit', 
    '#value' => isset($instrument->id) ? t('Update instrument') : t('Save instrument'),
    '#weight' => 50,
  );

  field_attach_form('instrument', $instrument, $form, $form_state);

  return $form;
}

/**
 * Submit handler for the musician add/edit form.
 */
function instrument_form_submit($form, &$form_state) {
  $instrument = entity_ui_form_submit_build_entity($form, $form_state);
  $instrument->save();
  drupal_set_message(t('The instrument: @name has been saved.', array('@name' => $instrument->name)));
  $form_state['redirect'] = 'admin/instruments';
}

/**
 * Implements hook_field_info().
 */
function setlist_field_info() { 
  
  return array(
    'setlist_player' => array(
      'label' => t('Player'),
      'description' => t('Custom Player Field'),
      'default_widget' => 'setlist_player_widget',
      'default_formatter' => 'setlist_player_formatter', 
    ),
  ); 
}

/**
 * Implements hook_field_widget_info().
 */
function setlist_field_widget_info() { 
  return array(
    'setlist_player_widget' => array(
      'label' => t('Default'),
      'field types' => array(
        'setlist_player'
      ),
      'behaviors' => array(
        'multiple values' => FIELD_BEHAVIOR_DEFAULT, 
        'default value' => FIELD_BEHAVIOR_DEFAULT,
      ), 
    ), 
  ); 
}

/**
 * Implements hook_field_widget_form().
 */
function setlist_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {

  /// \todo pull out existing values from form_state 

  $element += array(
    '#type' => 'fieldset', 
  );

  $required = $element['#required']; 
  $item =& $items[$delta];   

  $musicians = entity_load('musician', FALSE, NULL, TRUE);
  $musician_names = array('');
  foreach ($musicians as $key => $musician) {
    array_push($musician_names, $musician->name);
  }
  
  $element['musician'] = array( 
    '#title' => t('Musician'), 
    '#type' => 'textfield', 
    '#required' => $required, 
    '#attributes' => array('disabled' => 'disabled'),
    '#default_value' => isset($item['musician']) ? $item['musician'] : $musician_names[$delta], ); 

  $instruments = entity_load('instrument', FALSE, NULL, TRUE);
  $instrument_names = array('');
  
  foreach ($instruments as $key => $instrument) {
    array_push($instrument_names, $instrument->name);
  }
    
  $element['instrument'] = array( 
    '#title' => t('Instrument'), 
    '#type' => 'select', 
    '#required' => $required, 
    '#options' => $instrument_names,
    '#default_value' => isset($item['instrument']) ? $item['instrument'] : '', ); 
      
  return $element;
}

/**
 * Implements hook_field_is_empty().
 */
function setlist_field_is_empty($item, $field) { 
  $has_stuff = FALSE; 
   
  // has the user entered a musician and instrument? 
  if (!empty($item['musician']) && (!empty($item['instrument']))) { 
    $has_stuff = TRUE; 
  } 
  return !$has_stuff; 
}

/**
 * Implements hook_field_validate()
 */
function setlist_player_field_validate($entity_type, $entity, $field, $instance, $langcode, $items, &$errors) { 
  dpm($items);
  foreach ($items as $delta => $item) {
    dpm($item);
  }
}

function setlist_form_alter(&$form, &$form_state, $form_id)
{  
  if ($form_id == "song_form") {
    
    $form['#validate'][] = '_song_form_validate';
    $delta = $form_state['field']['field_player']['und']['items_count'];
    $lang = $form['field_player']['#language'];
    
    if ($delta < 1) {
      $player_field = $form['field_player'];  
      $fieldUnd = $player_field[$lang][0];
      
      $musicians = entity_load('musician', FALSE, NULL, TRUE);
      $count = 0;
      foreach ($musicians as $key => $musician) {
        if ($count == 0) {
          $form['field_player'][$lang][0]['musician']['#title'] = $musician->name;
          $form['field_player'][$lang][0]['musician']['#default_value'] = $musician->name;
        }
        else {
          $fieldUnd['musician']['#title'] = $musician->name;
          $fieldUnd['musician']['#default_value'] = $musician->name;
          array_push($form['field_player'][$lang], $fieldUnd);
        }
        
        $count++;
      }
    }
    else {
      // delete the last delta
      $max_delta = $form['field_player'][$lang]['#max_delta'];
      unset($form['field_player'][$lang][$max_delta]);
      $form['field_player'][$lang]['#max_delta'] = $max_delta-1;
      
    }
    
    $form['field_player'][$lang]['add_more']['#access'] = FALSE;
  }
}

/**
 * Implements hook_field_formatter_info().
 */
function setlist_field_formatter_info() {
  return array(
    'setlist_player_formatter' => array(
      'label' => t('Default'),
      'description' => t('Default formatter'),
      'field types' => array('test_field'),
      'settings' => array(
        'musician_setting' => 'Musician: ',
      ),
    ),
  );
}

function return_instrument($item)
{
    return $item->name;
}

/**
 * Implements hook_field_formatter_view().
 */
function setlist_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();
  $settings = $display['settings'];

  switch ($display['type']) {
    case 'setlist_player_formatter':
      $instruments = entity_load('instrument', FALSE, NULL, TRUE);
      $instrument_names = array_map("return_instrument", $instruments);

      foreach ($items as $delta => $item) {
	$name = $instrument_names[$item['instrument']];
        $element[$delta] = array('#markup' => $item['musician'] . ', Instrument: ' . $name);
      }
      break;
  }

  return $element;
}
